### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/@payloadcms%2fplugin-stripe: Not found

### ISSUE THREAD

**Issue by Etheliene** [payloadcms/plugin-stripe#1]
Is this plugin ready / published yet?

**Comment by jmikrut** [comment]
Hey @Etheliene - nope not yet! We will be building this one in public and releasing a boilerplate to go along with it. Gonna be good. But you can expect more here over the coming weeks!

**Comment by jacobsfletch** [comment]
Hi @Etheliene, super exciting to see you in need of this! We are in active development here, with a `0.0.1` released just now (resolves yarn error). This is a first beta release as we continue development in the coming weeks. You might be better off waiting for a stable `1.0.0` release instead of installing this, because the API and integration details are subject to change. 

If you have any specific integration details you'd like us to consider as we design this plugin, let us know!
