### ISSUE TITLE
How to sync images?

### ISSUE THREAD

**Issue by silveltman** [payloadcms/plugin-stripe#28]
A couple of things making it difficult to sync images:

- when using 'image' field as fieldPath, it is the image id, not the object.
- Stripe takes an 'images' array, not a string

Proposed solution: instead of 'fieldPath' being a string, allow it to be a function which return a value. This would allow us to use local API the get the image and return in in the right format; an array.

**Comment by jacobsfletch** [comment]
Hey @silveltman good question, and without looking too deeply into this right now, I think your solution is probably the right one 👍. Since the `sync` feature is a work-in-progres, I'm going to label this is an feature. I'll take look further into this as soon as I can.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-stripe) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4490), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
